<?php
/** @var \Magenest\Movie\Block\Widget\MovieList $block */

$movies = $block->getMovies();
?>

<div>
    <?php if ($movies->getSize() > 0): ?>

        <ol>
            <?php foreach ($movies as $movie): ?>
                <li>
                    <strong><?= $block->escapeHtml($movie->getName()) ?></strong>
                    - Rating: <?= $block->escapeHtml($movie->getRating()) ?>/10
                    - Director: <?= $block->escapeHtml($block->getDirector($movie->getDirectorId())->getName()) ?>
                </li>
            <?php endforeach; ?>
        </ol>

    <?php else: ?>
        <p><?= __('No movies found.') ?></p>
    <?php endif; ?>

</div>
