<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Customer\Block\Form\Register $block */
?>

<div class="field telephone">
    <label for="telephone" class="label">
        <span><?= $escaper->escapeHtml(__('Telephone')) ?></span>
    </label>
    <div class="control">
        <input type="tel"
               name="telephone"
               id="telephone"
               value="<?= $escaper->escapeHtmlAttr($block->getFormData()?->getTelephone() ?? '') ?>"               title="<?= $escaper->escapeHtmlAttr(__('Telephone')) ?>"
               class="input-text"
               placeholder="<?= $escaper->escapeHtmlAttr(__('0912345678 or +84912345678')) ?>">
    </div>
</div>
