<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Customer\Block\Form\Register $block */
?>

<div class="field telephone">
    <label for="phone_number" class="label">
        <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
    </label>
    <div class="control">
        <input type="tel"
               name="phone_number"
               id="phone_number"
               class="input-text"
               placeholder="<?= $escaper->escapeHtmlAttr(__('0912345678 or +84912345678')) ?>">
    </div>
</div>
