<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Customer\Block\Form\Edit $block */

?>

<?php
$customer = $block->getCustomer();
?>
<div class="field telephone">
    <label for="phone_number" class="label">
        <span><?= $escaper->escapeHtml(__('Phone Number')) ?></span>
    </label>
    <div class="control">
        <input type="tel"
               name="phone_number"
               id="phone_number"
               value="<?= $escaper->escapeHtmlAttr($customer->getCustomAttribute('phone_number') ? $customer->getCustomAttribute('phone_number')->getValue() : '') ?>"
               title="<?= $escaper->escapeHtmlAttr(__('Phone Number')) ?>"
               class="input-text"
               placeholder="<?= $escaper->escapeHtmlAttr(__('0912345678 or +84912345678')) ?>">
    </div>
</div>
